### ISSUE TITLE
Should we implement onDraw method instead of draw method?

### ISSUE THREAD

**Issue by pine** [mattak/ClipView#6]
Hi. I found that documents.

Is it correct that the way of overriding draw method 🤔 

>Manually render this view (and all of its children) to the given Canvas. The view must have already done a full layout before this function is called. When implementing a view, implement onDraw(android.graphics.Canvas) instead of overriding this method. If you do need to override this method, call the superclass version.

https://developer.android.com/reference/android/view/View.html#draw(android.graphics.Canvas)

Thank you.

**Comment by mattak** [comment]
👀

**Comment by mattak** [comment]
@pine OK! It seems to fix it. I appreciate it if you send me patch. 🍣

**Comment by pine** [comment]
Hi @mattak.

I tried that.
In conclusion, I was a mistake. We should override `draw`.

First, I could't implement this used by overriding `onDraw` method only. It is called before drew `ViewGroup`'s children, so it can't controll.

Next, I try to override `dispatchDraw` method. It can clip `ViewGroup`'s children but can't clip view self. This is a problem if it has a background.

![screen shot 2017-05-24 at 11 25 15 pm](https://cloud.githubusercontent.com/assets/5249050/26409293/1b2d82e4-40db-11e7-9c5b-157a8849593f.png)

I want to see this view on Android Studio UI preview beautifully.
What is the obstacle?

Thank you.

**Comment by mattak** [comment]
👀

**Comment by mattak** [comment]
Thank you for telling me the result.
Sorry, I have no idea how to show clipview beautifully on Android Studio previewer. 😢
